"""Adiciona campos detalhados para ItemAta (tipo, garantia, calibracao, etc)

Revision ID: 0e9dd444a2b7
Revises: 82a6a0e456ff
Create Date: 2025-05-28 15:41:00.346508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9dd444a2b7'
down_revision = '82a6a0e456ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_item', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_garantia_fim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requer_calibracao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ultima_calibracao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proxima_calibracao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reutilizavel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.drop_column('reutilizavel')
        batch_op.drop_column('proxima_calibracao')
        batch_op.drop_column('ultima_calibracao')
        batch_op.drop_column('requer_calibracao')
        batch_op.drop_column('data_garantia_fim')
        batch_op.drop_column('tipo_item')

    # ### end Alembic commands ###
