"""Adiciona UnidadeSaude e vincula a Contratinhos e Empenhos

Revision ID: 4562995d55ee
Revises: 0e9dd444a2b7
Create Date: 2025-05-28 16:13:17.890411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4562995d55ee'
down_revision = '0e9dd444a2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Linhas abaixo comentadas porque a tabela 'unidade_saude' já existe no banco de dados.
    # op.create_table('unidade_saude',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nome_unidade', sa.String(length=150), nullable=False),
    # sa.Column('tipo_unidade', sa.String(length=50), nullable=False),
    # sa.Column('endereco', sa.String(length=255), nullable=True),
    # sa.Column('telefone', sa.String(length=20), nullable=True),
    # sa.Column('email_responsavel', sa.String(length=120), nullable=True),
    # sa.Column('criado_em', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('nome_unidade')
    # )
    
    # As operações abaixo (adicionar colunas, criar chaves estrangeiras, alterar coluna)
    # devem ser executadas, pois provavelmente não foram aplicadas na tentativa anterior.
    with op.batch_alter_table('contratinho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_saude_id', sa.Integer(), nullable=True))
        # O nome da constraint (primeiro argumento) pode ser None, Alembic gerará um.
        # Certifique-se que 'unidade_saude.id' é o nome correto da coluna referenciada.
        batch_op.create_foreign_key('fk_contratinho_unidade_saude_id', 'unidade_saude', ['unidade_saude_id'], ['id'])

    with op.batch_alter_table('empenho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_saude_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_empenho_unidade_saude_id', 'unidade_saude', ['unidade_saude_id'], ['id'])

    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.alter_column('tipo_item',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.alter_column('tipo_item',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('empenho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidade_saude_id')

    with op.batch_alter_table('contratinho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidade_saude_id')

    op.drop_table('unidade_saude')
    # ### end Alembic commands ###
